MAX_LIDAR_DISTANCE = 2.8
STEERING_MULTIPLIER = 3.3
MINIMUM_SPEED = 30
MAXIMUM_SPEED = 80

DISPARITY_DISTANCE = 0.3
SAFETY_EXTENSION = 25

GAP_SELECTION = "best" # least_steering, widest, deepest, largest_integral
POINT_SELECTION = "best" # lear_steering, middle, deepest
MIN_GAP_SIZE = 10
MIN_GAP_DISTANCE = 1
CORNERING_DISTANCE = 0.28
